[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/portfolio_cv_pwa/"
# Whether to include hash values in the output file names.
filehash = false

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false

[[hooks]]
stage = "pre_build"
command = "npx"
command_arguments = [
  "tailwindcss",
  "-i",
  "public/tailwind_input.css",
  "-o",
  "public/tailwind_output.css",
]
